version: "2.4"
services:
  nginx:
    build: 
      context: .
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
      - ./config/nginx.conf:/etc/nginx/nginx.conf # need this to fix nginx 'caching' bugs
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
    ports: 
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
        - "./data/certbot/conf:/etc/letsencrypt"
        - "./data/certbot/www:/var/www/certbot"
        #- "./web:/var/www/html"
