version: '3.3'

services:
  mariadb:
    image: mariadb:10.4.11
    ports:
      - 3306:3306
    volumes:
      - ./apps/mysql:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=system

networks:
  default:
    external:
      name: laradock_backend
  #app-network  
